version: 2
jobs:
  build:
    working_directory: ~/src/CoPaymentGateway
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .

      - run: dotnet build
      - run: dotnet test --no-build ~/src/CoPaymentGateway/CoPaymentGateway.Tests
