version: 2
jobs:
  build_dir: ~/src/CoPaymentGateway
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build ~/src/CoPaymentGateway/CoPaymentGateway.Tests
