version: 2
jobs:
  build:
    working_directory: /CoPaymentGateway
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test --no-build CoPaymentGateway.Tests
