global:
  scrape_interval:     30s 
  evaluation_interval: 30s 

  external_labels:
    monitor: 'my-project'

scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 10s

    static_configs:
      - targets: ['prometheus:9090']
          
  - job_name: 'copaymentgateway'

    scrape_interval: 5s

    static_configs:
      - targets: ['copaymentgateway:80']
